// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dceaelgpabxxtvyadyzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZWFlbGdwYWJ4eHR2eWFkeXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTAwODAsImV4cCI6MjA2NTIyNjA4MH0.9noQ6dbj4j_8mtvuDwVk_m5laBcJsDDM34gg_zqFs3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);